config/routes.rb
Rails.application.routes.draw do

  get 'ports/suggest'

  get 'ports/route'

  get 'testing/new'

  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    # delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  root to: 'pages#home'

  resources :conversations, only: [:show, :new, :create, :update, :index] do
    get :unread, on: :collection
    resources :messages, only: [:create]
  end

  resources :feedbacks, only: [:show, :new, :create, :edit, :update, :destroy, :index]

  resources :itineraries, only: [:show, :new, :create, :edit, :update, :destroy, :index, :search] do
    post :search, on: :collection
    resources :build
  end

  resources :notifications, only: :index

  resources :users, constraints: { id: /[A-Za-z0-9\.]+/ }, only: [:create ,:show, :update, :destroy] do
    get :itineraries, on: :member
    resources :references, only: [:show, :new, :create, :update, :index]
  end

  # Admin Area
  namespace :admin do
    resources :users, only: [:index] do
      get :login_as, on: :member
      post :ban, :unban, on: :member
    end
  end

  mount Resque::Server, at: '/resque' if defined?(Resque::Server)

  # Root route aliases
  get :dashboard, to: 'users#dashboard'
  get :settings, to: 'users#settings'
  get :banned, to: 'users#banned'

  get :about, to: 'pages#about'
  get :how_it_works, to: 'pages#how_it_works'
  get :policy, to: 'pages#policy'
  get :terms, to: 'pages#terms'
  get :demo_terms, to: 'pages#demo_terms'
  get :fbjssdk_channel, to: 'pages#fbjssdk_channel'
  post :report_uri, to: 'pages#report_uri'

  post :search_itineraries_new, to: 'itineraries#new_search'

end

app/models/itineraries/search.rb
class Itineraries::Search
  include ActiveModel::Model

  attr_accessor :from, :to,
    :start_location_lat, :start_location_lng, :end_location_lat, :end_location_lng,
    :filter_round_trip, :filter_pink, :filter_verified, :filter_smoking_allowed, :filter_pets_allowed, :filter_driver_gender

  validates :from, presence: true
  validates :to, presence: true
end

app/models/itinerary.rb
class Itinerary
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paranoia
  include Mongoid::Geospatial
  include Mongoid::MultiParameterAttributes
  include Mongoid::Slug

  DAYNAME = %w(Sunday Monday Tuesday Wednesday Thursday Friday Saturday)

  belongs_to :user
  delegate :name, to: :user, prefix: true
  delegate :first_name, to: :user, prefix: true

  has_many :conversations, as: :conversable, dependent: :destroy

  # Details
  field :description
  field :num_people, type: Integer
  field :smoking_allowed, type: Boolean, default: false
  field :pets_allowed, type: Boolean, default: false
  field :price, type: Integer, default: 0
  field :days_at_sea, type: Integer, default: 0
  field :pink, type: Boolean, default: false
  field :round_trip, type: Boolean, default: false
  field :leave_date, type: DateTime
  field :return_date, type: DateTime
  field :daily, type: Boolean, default: false
  field :start_address, type: String
  field :end_address, type: String
  field :start_port_id, type: String
  field :end_port_id, type: String
  field :start_coords, type: String
  field :end_coords, type: String
  field :route_path, type: String


  # Cached user details (for filtering purposes)
  field :driver_gender
  field :verified

  slug :start_address, :end_address, reserve: %w(new)

  # default_scope -> { any_of({:leave_date.gte => Time.now.utc}, {:return_date.gte => Time.now.utc, round_trip: true}, { daily: true }) }

  validates :description, length: { maximum: 1000 }, presence: true
  validates :start_address, presence: true
  validates :end_address, presence: true
  validates :num_people, numericality: { only_integer: true, greater_than: 0, less_than: 10 }, allow_blank: true
  validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than: 10000 }
  validates :days_at_sea, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than: 10000 }
  validates :leave_date, timeliness: { on_or_after: -> { Time.now } }, on: :create
  validates :return_date, presence: true, if: -> { round_trip }

  validate :driver_is_female, if: -> { pink }
  validate :return_date_validator, if: -> { round_trip }

  def return_date_validator
    self.errors.add(:return_date,
                    I18n.t('mongoid.errors.messages.after',
                    restriction: leave_date.strftime(I18n.t('validates_timeliness.error_value_formats.datetime')))) if return_date && return_date <= leave_date
  end

  def driver_is_female
    self.errors.add(:pink, :driver_must_be_female) unless user.female?
  end

  before_create do
    self.driver_gender = user.gender
    self.verified = user.facebook_verified
    true
  end

  # after_create do
  #   begin
  #     # Resque.enqueue(FacebookTimelinePublisher, id) if share_on_facebook_timeline
  #   rescue Redis::CannotConnectError
  #   end
  # end

  def title
    [start_address, end_address].join ' - '
  end

  def to_s
     title || id
  end

  def static_map(width = 640, height = 360)
    URI.encode("http://maps.googleapis.com/maps/api/staticmap?size=#{width}x#{height}&scale=2&sensor=false&markers=color:green|label:B|#{end_coords}&markers=color:green|label:A|#{start_coords}&path=enc:#{route_path}")
  end

end

app/controllers/itineraries_controller.rb
class ItinerariesController < ApplicationController

  skip_before_action :authenticate_user!, only: [:show]

  before_action :set_itinerary, only: [:show]
  before_action :check_gender, only: [:show]

  before_action :check_permissions

  def new
    @itinerary = Itinerary.new
  end

  def index
    @itineraries = Itinerary.new
  end

  def show
    @conversation = @itinerary.conversations.find_or_initialize_by(user_ids: [current_user.id, @itinerary.user.id]) if current_user
    @reference = current_user.references.find_or_initialize_by(itinerary_id: @itinerary.id) if current_user
    session[:redirect_to] = itinerary_path(@itinerary) unless user_signed_in?
  end

  def create
    @itinerary = current_user.itineraries.new(permitted_params.itinerary)
    if @itinerary.save
      redirect_to itinerary_path(@itinerary), flash: { success: t('flash.itineraries.success.create') }
    else
      @itinerary.start_address = ''
      @itinerary.end_address = ''
      render :new
    end
  end

  def edit
    @itinerary = current_user.itineraries.find params[:id]
  end

  def update
    @itinerary = current_user.itineraries.find params[:id]
    if @itinerary.update_attributes permitted_params.itinerary
      redirect_to itinerary_path(@itinerary), flash: { success: t('flash.itineraries.success.update') }
    else
      render :edit
    end
  end

  def destroy
    @itinerary = current_user.itineraries.find params[:id]
    @itinerary.destroy
    redirect_to itineraries_user_path(current_user), flash: { success: t('flash.itineraries.success.destroy') }
  end

  def search
    @selected = Itinerary.find_by(start_address: 'Chennai, India')
    respond_to do |format|
      format.js
    end
  end

  def new_search
    itinerary_entries = params[:itinerary]
    @selected = Itinerary.all
    @selected = @selected.where(start_address: params[:start_address]) unless params[:start_address] == ''
    @selected = @selected.where(end_address: params[:end_address]) unless params[:end_address] == ''
    @selected = @selected.where(pink: true) if params[:toggle_tracker] == 'true' && itinerary_entries[:pink] == '1'
    @selected = @selected.where(round_trip: true) if params[:toggle_tracker] == 'true' && itinerary_entries[:round_trip] == '1'
    @selected = @selected.where(smoking_allowed: true) if params[:toggle_tracker] == 'true' && itinerary_entries[:smoking_allowed] == '1'
    @selected = @selected.where(pets_allowed: true) if params[:toggle_tracker] == 'true' && itinerary_entries[:pets_allowed] == '1'

    respond_to do |format|
      format.js { render 'new_search' }
      format.html { render 'new_search' }
    end
  end

  protected
  def check_permissions
  end

  def set_itinerary
    @itinerary = Itinerary.find params[:id]
  end

  def check_gender
    return unless @itinerary.pink?
    if !user_signed_in?
      redirect_to root_path
    elsif current_user.male?
      redirect_to :dashboard, flash: { error: t('flash.itineraries.error.pink') }
    end
  end
end

app/helpers/itineraries_helper.rb
module ItinerariesHelper
  def boolean_options_for_select
    @boolean_options_for_select ||= options_for_select [[t('boolean.true'), true], [t('boolean.false'), false]]
  end

  def default_leave_date
    @default_leave_date ||= ((Time.now).change(min: (Time.now.min / 10) * 10) + 10.minutes).in_time_zone
  end

  def boolean_tag(value, field)
    status = value ? 'allowed' : 'forbidden'
    content_tag :span, t(".#{field}.#{status}"), class: "tag tag-#{status}"
  end

  def share_on_facebook_timeline_checkbutton(form)
    publish_actions_permission = current_user.facebook_permission?(:publish_actions)
    if background_jobs_available?
      (form.label :share_on_facebook_timeline, class: "btn btn-fb btn-checkbox#{' disabled' unless publish_actions_permission}" do
        form.default_tag(:check_box, :share_on_facebook_timeline, disabled: !publish_actions_permission, checked: publish_actions_permission) +
        content_tag(:span, nil, class: 'fa fa-square-o check') + ' ' +
        Itinerary.human_attribute_name(:share_on_facebook_timeline)
      end) +
      (unless publish_actions_permission
        content_tag(:p, class: 'text-muted') do
          content_tag(:small) do
            content_tag(:span, nil, class: 'fa fa-ban') + ' ' +
            t('.missing_publish_actions_permission', appname: APP_CONFIG.app_name)
          end
        end
      end)
    else
      t('.share_on_timeline_unavailable', appname: APP_CONFIG.app_name)
    end
  end
end

app/views/itineraries/_form.html.slim
/!
  .control-group.hide
    .controls
      = label_tag nil, class: 'radio inline' do
        = f.default_tag :radio_button, :daily, false, class: 'inline', checked: true
        = t('.single_itinerary')
      | &nbsp;
      = label_tag nil, class: 'radio inline mock' do
        = f.default_tag :radio_button, :daily, true, class: 'inline'
        = t('.daily_itinerary')
.form-horizontal
  fieldset#single
    .form-group
      .col-sm-10.col-sm-offset-2= f.check_box :round_trip
    .form-group
      = f.label :leave_date, class: 'control-label col-sm-2'
      .col-sm-10= f.default_tag :datetime_select, :leave_date, { default: default_leave_date, start_year: Time.now.year, end_year: 1.year.from_now.year, minute_step: 10, ampm: t('time.ampm') }, class: 'form-control date-time'
    .form-group
      = f.label :return_date, class: 'control-label col-sm-2'
      .col-sm-10= f.default_tag :datetime_select, :return_date, { default: default_leave_date, start_year: Time.now.year, end_year: 1.year.from_now.year, minute_step: 10, ampm: t('time.ampm') }, class: 'form-control date-time', disabled: !@itinerary.round_trip
  fieldset#daily.hide.mock
    .control-group
      .controls
        table.table.table-condensed#daily-itinerary-table
          thead
            tr
              th
              th= t('.day')
              th= t('.leave_time')
              th= t('.return_time')
          tbody
            - (0..6).each_with_index do |index|
              tr
                td
                  p.text-center
                    = check_box_tag "day-#{index}"
                td= label_tag "day-# index ", t('date.day_names')[index]
                td
                  = time_select 'one', 'two', { minute_step: 10, default: { hour: 8 }, ampm: t('time.ampm') }, class: 'date-time', disabled: (index > 0)
                td
                  = time_select 'one', 'two', { minute_step: 10, default: { hour: 18 }, ampm: t('time.ampm') }, class: 'date-time', disabled: (index > 0)
          tfoot
            tr
              td colspan="2"
              td colspan="2"
                = label_tag 'edit-all-times', class: 'checkbox inline' do
                  = check_box_tag 'edit-all-times', nil, checked: true
                  = t('.edit_all_times')

  .form-group class=('has-error' if @itinerary.errors.include?(:price))
    = f.label :price, class: 'control-label col-sm-2'
    .col-sm-10
      .input-group.input-group-number
        = f.default_tag :text_field, :price, class: 'form-control'
        span.input-group-addon= APP_CONFIG.currency
      - if @itinerary.errors.include?(:price)
        span.help-inline
          = @itinerary.errors.messages[:price].join(', ')
      p.help-block#fuel-help data-avg-consumption=current_user.vehicle_avg_consumption
        span#fuel-help-text
  .form-group class=('has-error' if @itinerary.errors.include?(:days_at_sea))
    = f.label :days_at_sea, class: 'control-label col-sm-2'
    .col-sm-10
      .input-group.input-group-number
        = f.default_tag :text_field, :days_at_sea, class: 'form-control'
        span.input-group-addon= 'days'
      - if @itinerary.errors.include?(:days_at_sea)
        span.help-inline
          = @itinerary.errors.messages[:days_at_sea].join(', ')
  .form-group class=('has-error' if @itinerary.errors.include?(:description))
    = f.label :description, class: 'control-label col-sm-2'
    .col-sm-10
      = f.default_tag :text_area, :description, rows: 5, help: true, class: 'form-control'
      p.help-block= t('.description_help')
      - if @itinerary.errors.include?(:description)
        span.help-inline
          = @itinerary.errors.messages[:description].join(', ')
  .form-group
    .col-sm-10.col-sm-offset-2
      - if current_user.female?
        = f.check_box :pink, disabled: (current_user.male?), class: 'checkbox inline'
        p.help-block
          span.fa.fa-lock<>
          = t('.pink_help')
      = f.check_box :smoking_allowed, class: 'checkbox inline'
      = f.check_box :pets_allowed, class: 'checkbox inline'

app/views/itineraries/_header.html.slim
.page-header
  h1.no-margin-bottom= @itinerary.title
.row.itinerary-header
  .col-sm-6
    = image_tag @itinerary.static_map, class: 'google-static-map img-responsive', alt: ''
  .col-sm-6
    .media#user-media
      = link_to user_path(@itinerary.user), class: 'pull-left' do
        = user_profile_picture @itinerary.user, size: [70, 70], type: 'large', style: nil, opts: {class: 'img-circle'}
      .media-body
        h4.media-heading
          - if user_signed_in?
            = link_to @itinerary.user, user_path(@itinerary.user)
          - else
            = t('.app_user', appname: APP_CONFIG.app_name)
        p.text-muted= @itinerary.description
    .tag-list
      span.tag.tag-icare= Itinerary.human_attribute_name :start_address
      span.tag= @itinerary.start_address
    .tag-list
      span.tag.tag-icare= Itinerary.human_attribute_name :end_address
      span.tag= @itinerary.end_address
    - if @itinerary.daily?
    - else
      .tag-list
        span.tag.tag-icare= Itinerary.human_attribute_name :leave_date
        span.tag= l(@itinerary.leave_date, format: :long)
      - if @itinerary.round_trip?
        .tag-list
          span.tag.tag-icare= Itinerary.human_attribute_name :return_date
          span.tag= l(@itinerary.return_date, format: :long)
    .tag-list
      span.tag.tag-icare= t('.expenses_to_share')
      span.tag #{Itinerary.human_attribute_name(:price)}: #{@itinerary.price}#{APP_CONFIG.currency}
      span.tag #{Itinerary.human_attribute_name(:days_at_sea)}: #{@itinerary.days_at_sea} days
    .tag-list
      - if @itinerary.pink?
        span.tag.tag-pink rel='tooltip' title=t('itineraries.form.pink_help')
          span.fa.fa-lock<>
          = Itinerary.human_attribute_name(:pink)
      = boolean_tag @itinerary.smoking_allowed?, 'smoking'
      = boolean_tag @itinerary.pets_allowed?, 'pets'

app/views/itineraries/_opengraph_head_contents.html.slim
- content_for :head do
  - fb_namespace = APP_CONFIG.facebook.namespace
  meta property='fb:app_id' content=APP_CONFIG.facebook.app_id
  meta property='og:url' content=itinerary_url(itinerary)
  meta property='og:site_name' content=APP_CONFIG.app_name
  meta property='og:type' content="#{fb_namespace}:itinerary"
  meta property='og:title' content=itinerary.title
  meta property='og:image' content=itinerary.static_map
  meta property='og:description' content=itinerary.description

app/views/itineraries/_route_step.html.slim
.row
  .col-sm-4
    = f.text_field :start_address, autocomplete: 'off'
    .coords id='start_coords'
      = 'Coordinates: '
    = f.text_field :end_address, autocomplete: 'off'
    .coords id='end_coords'
      = 'Coordinates: '
    = f.hidden_field :start_port_id
    = f.hidden_field :end_port_id
    #result.alert.alert-info
      = t('.distance')
      b#distance<
      br
      = t('.duration')
      b#duration<
    #incomplete-setup.alert.alert-info.hide
      = 'Please setup a route to continue further'
    .form-group
      = f.default_tag :button, t('.get_route'), type: 'button', class: 'btn btn-primary', id: 'get-route'
      = image_tag 'ajax-spinner-24x17.gif', width: 24, height: 17, alt: '...', id: 'itineraries-spinner', class: 'hide'
    #error.alert.alert-danger
  .col-sm-8
    #new-itinerary-map.google-maps
    | <small class='map-credits pull-right'>Powered by <a href='http://www.vesseltracker.com' target='_blank'>VesselTracker</a></small>
.row
  .col-sm-4
    h3
      span.fa.fa-plus-circle<>
      = 'We are adding new locations'
    p
      = 'If you are not able to find the location you want, please raise it to us. We are working hard to push in as many locations as possible. '
      = link_to 'Feedback', feedbacks_path
  .col-sm-4
    h3
      span.fa.fa-eye-slash<>
      = t('.hint_privacy_title')
    p
      = t('.hint_privacy_content')
  .col-sm-4
    h3
      span.fa.fa-search<>
      = t('.hint_search_before_title')
    p
      = t('.hint_search_before_content', search_link: (link_to t('.search_link'), itineraries_path)).html_safe

app/views/itineraries/_search.html.slim
= bootstrap_form_for @itineraries, url: search_itineraries_new_path, method: :post, validate: false, remote: true do |f|
  = f.text_field :start_address, name: 'start_address', label: Itinerary.human_attribute_name(:start_address), id: 'itinerary_start_address'
  = f.text_field :end_address, name: 'end_address', label: Itinerary.human_attribute_name(:end_address), id: 'itinerary_end_address'
  = link_to '#', id: 'search-form-advanced-link' do
    span.fa.fa-chevron-down<>
    = t('.advanced_search')
    = f.hidden_field :route_path, name: 'toggle_tracker', id: 'toggle-tracker'
  #search-form-advanced
    .form-group
      - if current_user.female?
        = f.check_box :pink, name: 'pink', label: Itinerary.human_attribute_name(:pink)
        .checkbox
          p.help-block
            span.fa.fa-lock<>
            = t('itineraries.form.pink_help')
      = f.check_box :round_trip, label: Itinerary.human_attribute_name(:round_trip)
      = f.check_box :smoking_allowed, label: Itinerary.human_attribute_name(:smoking_allowed)
      = f.check_box :pets_allowed, label: Itinerary.human_attribute_name(:pets_allowed)
  .form-group
    = f.default_tag :button, t('.search'), type: 'submit', class: 'btn btn-primary', id: 'itineraries-search'
    = image_tag 'ajax-spinner-24x17.gif', width: 24, height: 17, alt: '...', id: 'itineraries-spinner', class: 'hide'

app/views/itineraries/_table.html.slim
.table-responsive
  table.table.table-itinerary
    thead
      tr
        th= Itinerary.human_attribute_name(:start_address)
        th= Itinerary.human_attribute_name(:end_address)
        th
          span.visible-xs
            span.fa.fa-info-circle rel='tooltip' title=t('itineraries.common.features')
          span.hidden-xs= t('itineraries.common.features')
        - if edit
          th= t('helpers.actions')
        - else
          th= User.model_name.human
          th= Itinerary.human_attribute_name(:leave_date)
    tbody
      - for itinerary in itineraries
        tr.vertical-align-middle
          td= link_to itinerary.start_address, itinerary_path(itinerary)
          td= link_to itinerary.end_address, itinerary_path(itinerary)
          td
            - if itinerary.pink
              span.text-pink.fa-fw.fa.fa-lock rel='tooltip' title=Itinerary.human_attribute_name(:pink)
            - if itinerary.daily
              span.fa-fw.fa.fa-repeat rel='tooltip' title=Itinerary.human_attribute_name(:daily)
            - if itinerary.round_trip
              span.fa-fw.fa.fa-exchange rel='tooltip' title=Itinerary.human_attribute_name(:round_trip)
          - if edit
            td
              .btn-toolbar
                = link_to edit_itinerary_path(itinerary), class: 'btn btn-xs btn-default' do
                  span.fa.fa-pencil<>
                  = t('helpers.links.edit')
                = link_to itinerary_path(itinerary), method: :delete, data: { confirm: t('helpers.links.confirm') }, class: 'btn btn-xs btn-danger' do
                  span.fa.fa-times<>
                  = t('helpers.links.destroy')
          - else
            td= link_to itinerary.user, user_path(itinerary.user)
            td= l(itinerary.leave_date.in_time_zone, format: :short)

app/views/itineraries/_table_new.html.erb
<% if !itineraries.empty? %>
    <% itineraries.each do |itinerary| %>
        <div class="row dashboard_cards">
          <div class="col-sm-2 text-center img-rounded">
            <%= user_profile_picture itinerary.user, size: [100, 100], type: 'large', style: nil, opts: {class: 'dashboard_cards_img img-circle'} %>
            <br>
            <span><%= itinerary.user %></span><br><br>
          </div>
          <div class="col-sm-8">
            <div class="row">
              <div class="col-xs-6">
                <h4 class="itinerary-title">
                  <small>From:</small> <%= itinerary.start_address %>
                </h4>
              </div>
              <div class="col-xs-6">
                <h4 class="itinerary-title">
                  <small>To:</small> <%= itinerary.end_address %>
                </h4>
              </div>
            </div>
            <div class="row dashboard_description"">
            <span><%= itinerary.description[0..350].gsub(/\s\w+\s*$/,'...') %></span>
          </div>
          <div class="row text-muted pull-right">
            <i>Leaving on <%= l(itinerary.leave_date.in_time_zone, format: :short) %></i>
          </div>
        </div>
        <div class="col-sm-2 text-center dashboard_itinerary_icons">
          <% if itinerary.pink %>
              <i class="fa fa-lock" title="Female only trip"></i>
          <% end %>
          <% if itinerary.daily %>
              <i class="fa fa-repeat" title="Daily trip"></i>
          <% end %>
          <% if itinerary.round_trip %>
              <i class="fa fa-exchange" title="Two way trip"></i>
          <% end %>
          <% if !itinerary.smoking_allowed %>
              <i class="fa flaticon-no-smoking2" title="Smoking not allowed"></i>
          <% end %>
          <% if !itinerary.pets_allowed %>
              <i class="fa flaticon-dog7" title="Pets not allowed"></i><br>
          <% end %>
          <span class="text-muted m-t-lg"><strong>Price: </strong><%= itinerary.price %><%= APP_CONFIG.currency %></span>
          <%= link_to "More Info", itinerary_path(itinerary), class: "btn btn-primary" %>
        </div>
        </div>
    <% end %>
    <% else %>
        <div class="row text-center" id="dummy_dashboard_card">
          <span class="text-muted">No entries found.</span>
        </div>
<% end %>

app/views/itineraries/edit.html.slim
- title t('.title')
.container
  == render 'header'
  = bootstrap_form_for @itinerary, validate: true, html: { class: 'form-horizontal' } do |f|
    = f.error_messages
    == render 'form', f: f
    .form-group
      .col-sm-10.col-sm-offset-2
        = f.submit class: 'btn btn-primary', data: { disable_with: t('helpers.disable_with') }

app/views/itineraries/index.html.slim
- title t('.title')
.container
  .row
    .col-sm-4
      h3= yield :title
      == render 'search'
      #error.alert.alert-danger
    .col-sm-8
      #new-itinerary-map.google-maps
      #itineraries-thumbs.row
  h3= 'Search Results'
  .row#search-results-new
    == render 'itineraries/table_new', itineraries: @latest_itineraries, edit: false if !@latest_itineraries.nil?

  | <script async defer
              src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDkEQUnCf2y4-7L8ONawU_mmO5hJsXCmzg&libraries=geometry&callback=initMap">
            </script>

app/views/itineraries/new.html.slim
- title t('.title')
.container
  - if @itinerary.errors.any?
    .alert.alert-danger.fade.in
      button type='button' class='close' data-dismiss='alert' &times;
      h4.alert-heading= t('errors.template.header', model: Itinerary.model_name.human, count: @itinerary.errors.size)
      = t('errors.template.body')
      ul
        - for message in @itinerary.errors.full_messages
          li= message
  .row
    .col-sm-6
      #wizard-step-1-title.itinerary-step.active
        h3= t('.plan_route')
    .col-sm-6
      #wizard-step-2-title.itinerary-step.hidden-xs
        h3= t('.insert_details_and_confirm')
  = bootstrap_form_for @itinerary, validate: false do |f|
    .form-group
      #wizard-step-1-content data-step='1'
        == render 'route_step', f: f
      #wizard-step-2-content.hide data-step='2'
        .row
          .col-sm-4
            = image_tag transparent_gif_image_data, class: 'img-responsive google-static-map', id: 'itinerary-preview-image', alt: ''
          .col-sm-8
            h1.itinerary-title
              small= Itinerary.human_attribute_name :start_address
              span#itinerary-preview-from
              small= Itinerary.human_attribute_name :end_address
              span#itinerary-preview-to
        == render 'form', f: f
        .text-center= share_on_facebook_timeline_checkbutton(f)
    .form-group.text-center
      = f.hidden_field :start_coords
      = f.hidden_field :end_coords
      = f.hidden_field :route_path
      .btn-toolbar
        = button_tag t('.previous_step'), type: 'button', class: 'btn btn-lg btn-default hide', name: 'back_button', id: 'wizard-prev-step-button'
        = f.submit t('.next_step'), type: 'button', class: 'btn btn-lg btn-primary', name: 'next_button', id: 'wizard-next-step-button', disabled: false
        = f.submit t('.confirm_and_share'), class: 'btn btn-lg btn-primary hide', id: 'new_itinerary_submit', data: { disable_with: t('helpers.disable_with') }
| <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDkEQUnCf2y4-7L8ONawU_mmO5hJsXCmzg&libraries=geometry&callback=initMap">
          </script>

app/views/itineraries/show.html.slim
- title @itinerary.title
== render 'opengraph_head_contents', itinerary: @itinerary
.container
  == render 'shared/flash_messages'
  == render 'header'
  hr
  .btn-toolbar.text-center
    - if user_signed_in?
      - if current_user != @itinerary.user
        = link_to new_or_show_conversation_path(@conversation), class: 'btn btn-lg btn-primary' do
          span.fa.fa-comment<>
          = t('.contact', user: @itinerary.user_first_name)
        = link_to new_or_show_reference_path(@reference, @itinerary), class: 'btn btn-lg btn-default' do
          span.fa.fa-thumbs-up<>
          = t('.send_reference')
        .btn-group
          button.btn.btn-lg.btn-warning
            span.fa.fa-flag<>
          button.btn.btn-lg.btn-warning.dropdown-toggle data-toggle='dropdown'
            span.caret
          ul.dropdown-menu role='menu'
            li= link_to t('.report_itinerary'), '#'
      - else
        = link_to edit_itinerary_path(@itinerary), class: 'btn btn-lg btn-default' do
          span.fa.fa-pencil<>
          = t('helpers.titles.edit', model: Itinerary.model_name.human)
    - else
      = link_to user_omniauth_authorize_path(provider: :facebook), class: 'btn btn-lg btn-fb', data: { no_turbolink: true } do
        span.fa.fa-facebook-square<>
        = t('.login_to_contact')