config/routes.rb
Rails.application.routes.draw do

  get 'ports/suggest'

  get 'ports/route'

  get 'testing/new'

  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    # delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  root to: 'pages#home'

  resources :conversations, only: [:show, :new, :create, :update, :index] do
    get :unread, on: :collection
    resources :messages, only: [:create]
  end

  resources :feedbacks, only: [:show, :new, :create, :edit, :update, :destroy, :index]

  resources :itineraries, only: [:show, :new, :create, :edit, :update, :destroy, :index, :search] do
    post :search, on: :collection
    resources :build
  end

  resources :notifications, only: :index

  resources :users, constraints: { id: /[A-Za-z0-9\.]+/ }, only: [:create ,:show, :update, :destroy] do
    get :itineraries, on: :member
    resources :references, only: [:show, :new, :create, :update, :index]
  end

  # Admin Area
  namespace :admin do
    resources :users, only: [:index] do
      get :login_as, on: :member
      post :ban, :unban, on: :member
    end
  end

  mount Resque::Server, at: '/resque' if defined?(Resque::Server)

  # Root route aliases
  get :dashboard, to: 'users#dashboard'
  get :settings, to: 'users#settings'
  get :banned, to: 'users#banned'

  get :about, to: 'pages#about'
  get :how_it_works, to: 'pages#how_it_works'
  get :policy, to: 'pages#policy'
  get :terms, to: 'pages#terms'
  get :demo_terms, to: 'pages#demo_terms'
  get :fbjssdk_channel, to: 'pages#fbjssdk_channel'
  post :report_uri, to: 'pages#report_uri'

  post :search_itineraries_new, to: 'itineraries#new_search'

end

app/models/concerns/user/authentication.rb
module Concerns
  module User
    module Authentication
      extend ActiveSupport::Concern

      included do
        def set_fields_from_omniauth(auth)
          # Auth / Credentials (token, expires_at)
          set_credentials auth.credentials

          # Info (email, name, verified)
          set_info auth.info

          # Extra raw info (username, gender, bio, languages)
          set_extra_raw_info auth.extra.raw_info

          # Extra raw info requiring special permissions (birthday, work, education)
          set_extra_raw_info_special_permissions auth.extra.raw_info

          # Locale, with priority to application setting
          self.locale = auth.extra.raw_info.locale.gsub(/_/,'-') if auth.extra.raw_info.locale && !self.locale?

          # Username and uid array
          self.username_or_uid = [ username, uid ]

          # Permissions
          set_permissions

          # Schedule facebook data cache
          Resque.enqueue(FacebookDataCacher, id)
        rescue Redis::CannotConnectError
        end

        def can_access?
          return true unless APP_CONFIG.facebook.restricted_group_id
          facebook do |fb|
            groups = fb.get_connections('me', 'groups')
            group = groups.select{ |g| g['id'] == APP_CONFIG.facebook.restricted_group_id }.first
            self.admin = group.present? && group['administrator']
            group.present?
          end
        end

        private
        def set_credentials(credentials)
          self.oauth_token = credentials.token
          self.oauth_expires_at = Time.at credentials.expires_at
        end

        def set_info(info)
          self.email = info.email
          self.name = info.name
          self.gender = info.gender.titleize if info.gender != nil
          self.facebook_verified = true
        end

        def set_extra_raw_info(raw_info)
          self.username = raw_info.username
          self.gender = raw_info.gender.titleize if self.gender == nil
          self.bio = raw_info.bio
          self.languages = raw_info.languages || []
        end

        def set_extra_raw_info_special_permissions(raw_info)
          self.birthday = Date.strptime(raw_info.birthday, '%m/%d/%Y').at_midnight if raw_info.birthday
          self.work = raw_info.work || []
          self.education = raw_info.education || []
        end

        def set_permissions
          facebook do |fb|
            self.facebook_permissions = fb.get_connections('me', 'permissions')[0]
          end
        end
      end

      module ClassMethods
        def from_omniauth(auth)
          where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
            user.provider = auth.provider
            user.uid = auth.uid
            user.password = Devise.friendly_token[0,20]
            user.set_fields_from_omniauth auth
            user.skip_confirmation!
            user.save!
          end
        end
      end
    end
  end
end

app/models/concerns/user/facebook.rb
module Concerns
  module User
    module Facebook
      extend ActiveSupport::Concern

      included do
        def facebook
          @facebook ||= Koala::Facebook::API.new(oauth_token)
          block_given? ? yield(@facebook) : @facebook
        rescue Koala::Facebook::APIError => e
          logger.info e.to_s
          nil # or consider a custom null object
          # TODO: Investigate this error:
          # Koala::Facebook::APIError: OAuthException: Error validating access token: Session does not match current stored session. This may be because the user changed the password since the time the session was created or Facebook has changed the session for security reasons.
        end

        def facebook_permission?(scope)
          facebook_permissions[scope.to_s].to_i == 1 if facebook_permissions?
        end

        def cache_facebook_data?
          favorites = %w(music books movies television games activities interests) # athletes sports_teams sports inspirational_people
          facebook do |fb|
            result = fb.batch do |batch_api|
              batch_api.get_connections('me', 'friends')
              favorites.each do |favorite|
                batch_api.get_connections('me', favorite)
              end
            end
            if result.any?
              self.facebook_friends = result[0] ? result[0].to_a : []
              self.facebook_favorites = result[1] ? result[1..-1].flatten : []
              return true
            end
          end
          false
        end
      end

      module ClassMethods
      end
    end
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paranoia

  # Concerns
  include ::Concerns::User::Authentication
  include ::Concerns::User::Facebook

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable,
         :trackable, :validatable, :confirmable, :lockable, :omniauthable, omniauth_providers: [:facebook]

  ## Database authenticatable
  field :email, type: String
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  field :confirmation_token,   type: String
  field :confirmed_at,         type: Time
  field :confirmation_sent_at, type: Time
  field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  field :locked_at,       type: Time

  GENDER = %w(Male Female)

  paginates_per 25

  index(username_or_uid: 1)

  has_and_belongs_to_many :conversations

  has_many :itineraries, dependent: :destroy
  has_many :feedbacks

  embeds_many :notifications
  embeds_many :references, cascade_callbacks: true

  # Auth / Credentials / Permissions
  field :provider
  field :uid
  field :oauth_token
  field :oauth_expires_at
  field :facebook_permissions, type: Hash, default: {}

  # Cached Facebook data
  field :facebook_friends, type: Array, default: []
  field :facebook_favorites, type: Array, default: []
  field :facebook_data_cached_at, type: DateTime, default: '2012-09-06'

  # Info
  field :name
  field :facebook_verified, type: Boolean, default: false

  # Extra
  field :username
  field :gender
  field :bio
  field :languages, type: Array, default: []

  # More info requiring special permissions
  field :birthday, type: Date
  field :work, type: Array, default: []
  field :education, type: Array, default: []

  # Icare
  field :username_or_uid
  field :vehicle_avg_consumption, type: Float, default: APP_CONFIG.fuel_consumption

  # Account
  field :locale
  field :time_zone, default: 'UTC' # NOTE think about it
  field :telephone
  field :admin, type: Boolean, default: false

  # field :access_level, type: Integer, default: 0
  field :banned, type: Boolean, default: false

  field :send_email_messages, type: Boolean, default: false
  field :send_email_references, type: Boolean, default: false

  validates :gender, inclusion: GENDER, allow_blank: true
  validates :time_zone, inclusion: ActiveSupport::TimeZone.zones_map(&:name).keys, allow_blank: true
  validates :vehicle_avg_consumption, numericality: { greater_than: 0, less_than: 10 }, presence: true
  # validates :access_level, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }

  #Validates the presence of name and email
  # validates :name, presence: true
  # VALID_EMAIL_REGEX = /\A[\w]+[\w+\-.]*@[\w\-]+(\.[\w\-]+)*\.[a-z]+\z/i
  # validates :email, presence: true, length: { maximum: 255 },
  #           format: { with: VALID_EMAIL_REGEX },
  #           uniqueness: { case_sensitive: false }
  #
  #
  # #Implements Secure Password from ActiveModel of Rails
  # has_secure_password
  # validates :password, presence: true, length: { minimum: 6 }, on: :create


  def age
    ((Time.now.to_s(:number).to_i - birthday.to_time.to_s(:number).to_i) / 10e9.to_i) if birthday?
  end

  def first_name
    @first_name ||= name.split[0] if name?
  end

  def last_name
    @last_name ||= name.split[1] if name.count(' ') > 0
  end

  def to_s
    name || id
  end

  def to_param
    username || uid || id
  end

  def profile_picture(type = 'square')
    "http://graph.facebook.com/#{uid}/picture?type=#{type}"
  end

  def unread_conversations_count
    conversations.unread(self).size
  end

  def unread_references_count
    references.unread.size
  end

  def male?
    gender == 'Male'
  end

  def female?
    gender == 'Female'
  end

  def facebook?
    provider == 'facebook'
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_user, only: [:login_as, :ban, :unban]
  before_action :prevent_autoban, only: [:ban, :unban]

  def index
    @users = User.asc(:name).page params[:page]
  end

  def login_as
    sign_in_and_redirect :user, @user
  end

  def ban
    if @user.update_attributes(banned: true)
      redirect_to admin_users_path, flash: { success: t('flash.admin.users.success.ban') }
    else
      redirect_to admin_users_path, flash: { error: t('flash.admin.users.error.ban') }
    end
  end

  def unban
    if @user.update_attributes(banned: false)
      redirect_to admin_users_path, flash: { success: t('flash.admin.users.success.unban') }
    else
      redirect_to admin_users_path, flash: { error: t('flash.admin.users.error.unban') }
    end
  end

  private
  def set_user
    @user = User.find params[:id]
  end

  def prevent_autoban
    redirect_to admin_users_path, flash: { error: t('flash.admin.users.error.ban') } if @user == current_user
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    if @user = User.from_omniauth(request.env['omniauth.auth'])
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
    else
      redirect_to root_path, flash: { error: t(APP_CONFIG.facebook.restricted_group_id ? 'flash.sessions.error.restricted' : 'flash.sessions.error.create') }
    end
  end

  protected
  def after_omniauth_failure_path_for(scope)
    root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user_as_current_user, only: [:update, :dashboard, :settings, :itineraries]

  before_action :authenticate_user!, :except => [:new, :create]

  layout 'devise', only: [:new, :create]

  def show
    @user = find_user params[:id]
  end

  def new
  end

  def create
  end

  def update
    if @user.update_attributes(permitted_params.update_user)
      redirect_to :settings, flash: { success: t('flash.users.success.update') }
    else
      render :settings
    end
  end

  def destroy
    current_user.destroy
    session[:user_id] = nil
    redirect_to root_path, flash: { success: t('flash.users.success.destroy') }
  end

  def dashboard
    @latest_itineraries = Itinerary.includes(:user).desc(:created_at).limit 10

    # Gender filter
    @latest_itineraries = @latest_itineraries.where(pink: false) if current_user.male?
  end

  def itineraries
    @itineraries = @user.itineraries.desc :created_at
  end

  def banned
    redirect_to root_path unless current_user.banned?
  end

  private
  def set_user_as_current_user
    @user = current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper

  def facebook_profile_picture(user, type = :square)
    if user_signed_in?
      "//graph.facebook.com/#{user.class == User ? user.uid : user}/picture?type=#{type}"
    else
      '//fbstatic-a.akamaihd.net/rsrc.php/v2/yo/r/UlIqmHJn-SK.gif'
    end
  end

  def user_profile_picture(user, size: [50, 50], type: :square, style: 'img-responsive', opts: {})
    tag :img,
        { width: ("#{size[0]}px" if size),
          height: ("#{size[1]}px" if size),
          src: facebook_profile_picture(user, type),
          alt: '',
          class: [('verified' if user.class == User.model_name && user.facebook_verified?), style].compact.join(' ')
        }.merge(opts)
  end

  def friends_with_privacy(friends)
    case friends
    when 0...10
      '10-'
    when 10...100
      "#{friends / 10}0+"
    when 100...1000
      "#{friends / 100}00+"
    when 1000...5000
      "#{friends / 1000}000+"
    else
      '5000'
    end
  end

  def mutual_friends(user1, user2, limit = 5)
    return if user1 == user2
    mutual_friends_list = user1.facebook_friends & user2.facebook_friends
    return unless mutual_friends_list.any?
    html = content_tag(:div, t('.common_friends'), class: 'tag tag-facebook')
    mutual_friends_list.sample(limit).each do |mutual_friend|
      html << render_mutual_friend(mutual_friend)
    end
    html << link_to(t('.and_others', count: mutual_friends_list.size - 5), '#', class: 'disabled tag mock') if mutual_friends_list.size - 5 > 0
    html
  end

  def language_tags(user)
    return unless user.languages && user.languages.any?
    render_common_tags = (user != current_user)
    render_tags user.languages, current_user.languages, render_common_tags: render_common_tags, content: t('.likes'), class: 'description-facebook'

    common_languages = get_common_tags(current_user.languages, user.languages) if render_common_tags
    html = user.languages.map { |language| render_tag t('.language', language: language['name']), (render_common_tags && common_languages.include?(language['id'])) }
    html.join.html_safe
  end

  def work_and_education_tags(user, field)
    return unless user[field] && user[field].any?
    user_work_or_edu = remap_work_or_edu_tags(user[field], field)
    my_field = current_user[field]
    if (render_common_work_or_edu = (user != current_user) && my_field && my_field.any?)
      my_work_or_edu = remap_work_or_edu_tags(my_field, field)
    end
    render_tags user_work_or_edu, my_work_or_edu, render_common_tags: render_common_work_or_edu, content: User.human_attribute_name(field), class: 'tag tag-facebook'
  end

  def favorite_tags(user, user_favorites)
    return unless user_favorites && user_favorites.any?
    render_tags user_favorites, current_user.facebook_favorites, render_common_tags: (user != current_user), content: t('.likes'), class: 'tag tag-facebook tag-sm', css_class: 'tag-sm'
  end

  private
  def remap_work_or_edu_tags(field, type)
    key = (type == :work ? 'employer' : 'school')
    field.map { |h| { 'name' => h[key]['name'], 'id' => h[key]['id'] } }
  end

  def get_common_tags(my_tags, user_tags)
    return [] if my_tags.nil? || my_tags.empty?
    my_tags.map { |tag| tag['id'] } & user_tags.map { |tag| tag['id'] }
  end

  def render_mutual_friend(mutual_friend)
    content_tag(:div, class: 'tag tag-mutual-friend') do
      user_profile_picture(mutual_friend['id'], size: [25,25], style: nil) +
      mutual_friend['name']
    end
  end

  def render_tags(user_tags, my_tags, opts = {})
    options = { render_common_tags: false }.merge(opts)
    common_tags = get_common_tags(my_tags, user_tags) if options[:render_common_tags]
    html = content_tag(:div, options[:content], class: options[:class])
    user_tags.each do |tag|
      html << render_tag(tag['name'], options[:render_common_tags] && common_tags.include?(tag['id']), css_class = options[:css_class])
    end
    html
  end

  def render_tag(tag_text, common, css_class = nil)
    content_tag :div, tag_text, class: ['tag', ('tag-common' if common), css_class].compact.join(' ')
  end
end

app/views/users/_calculator.html.slim
.modal.hide#fuel-cost-calculator
  .modal-header
    btn.close type='button' data-dismiss='modal' &times;
    h3 Calcola consumi
  .modal-body
    = form_tag "consumption-calculator-form", class: "form-horizontal" do
      .control-group
        = label_tag :fuel_type, t(".fuel_type"), class: "control-label"
        .controls
          = select_tag :fuel_type, options_for_select(%w(diesel petrol lpg methane).map { |f| [t(".fuel_#{f}"), f] })
      .control-group
        = label_tag :vehicle_type, t(".vehicle_type"), class: "control-label"
        .controls
          = select_tag :vehicle_type, options_for_select(%w(compact standard high_consumption).map { |f| [t(".vehicle_#{f}"), f] }, selected: "standard")
      .control-group
        = label_tag :fuel_price, t(".fuel_price"), class: "control-label"
        .controls
          .input-append
            = text_field_tag :fuel_price, nil, class: "input-mini text-right"
            span.add-on
              = t(".100_km")
      .control-group
        = label_tag :fuel_price, t(".fuel_price"), class: "control-label"
        .controls
          .input-append
            = text_field_tag :fuel_price, nil, class: "input-mini text-right"
            span.add-on
              | &euro;
              = t(".per_liter")
          p.help-block
            | Prezzi medi al 16/07/2012: Benzina: 1,758 - Diesel: 1,649 - GPL: 0,741 - Metano: 0,972
      .control-group
        .controls
          h3
            #{t(".fuel_cost_estimate")}:
            span#fuel-cost
            span &euro; / km
  .modal-footer
    = link_to t("save"), "#", data: { dismiss: "modal" }, id: "save-fuel-cost", class: "btn btn-primary"
    = link_to t("close"), "#", data: { dismiss: "modal" }, class: "btn"

app/views/users/banned.html.slim
- title t('.title')
.container
  .page-header.text-center
    h1.text-danger
      span.fa.fa-ban<>
      = t('.you_were_banned')
    p.lead= t('.banned_description_html')

app/views/users/dashboard.html.slim
- title t('.title')
.container
  == render 'shared/flash_messages'
  ul.nav.nav-justified.lead
    li
      = link_to itineraries_path do
        span.fa.fa-search<>
        = t('.search_itineraries')
    li
      = link_to new_itinerary_path do
        span.fa.fa-plus<>
        = t('.new_itinerary')
    li
      = link_to itineraries_user_path(current_user) do
        span.fa.flaticon-transport524<>
        = t('.your_itineraries')
  h3= t('.latest_itineraries')
  == render 'itineraries/table_new', itineraries: @latest_itineraries, edit: false

app/views/users/itineraries.html.slim
- title t('.title')
.container
  == render 'shared/flash_messages'
  .page-header
    h1= yield :title
  == render 'itineraries/table', itineraries: @itineraries, edit: true

app/views/users/new.html.erb
<h3 class="loginlayout-bluetext">Register at CoSail</h3>
  <p>Create an account to see it in action</p>
    <%= form_for @user, html: {class: 'm-t', role: 'form'} do |f| %>
    <%= render 'shared/login_error_messages' %>
    <div class="form-group">
      <%= f.text_field :name, class: 'form-control', placeholder: 'Name', required: '' %>
    </div>
    <div class="form-group">
      <%= f.text_field :email, class: 'form-control', placeholder: 'email', type: 'email', required: '' %>
    </div>
      <div class="form-group">
        <%= f.text_field :password, class: 'form-control', placeholder: 'Password', type: 'password', required: '' %>
      </div>
    <div class="form-group">
      <%= f.text_field :password_confirmation, class: 'form-control', placeholder: 'Repeat Password', type: 'password', required: '' %>
    </div>
    <div class="form-group" id="data_1">
      <div class="input-group date">
        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
        <%= f.text_field :birthday, class: 'form-control', placeholder: 'Date of Birth', required: '' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.select(:gender, User::GENDER, {prompt: 'Gender', include_blank: false}, {class: 'form-control', required: ''} ) %>
    </div>
        <%= f.submit "Register", class: "btn btn-info block full-width m-b" %>

    <p class="text-muted text-center loginlayout-bluetext"><small>Want to explore other options?</small></p>
    <div class="row">
      <div class="col-sm-5 p-xxs">
        <a class="btn btn-sm btn-primary btn-block" href="<%= login_path %>">Login</a>
      </div>
      <div class="col-sm-7 p-xxs">
        <a class="btn btn-sm btn-fb-login btn-block" href="<%= user_omniauth_authorize_path(provider: :facebook) %>">
          <span class="fa fa-facebook-square"></span> Login with Facebook
        </a>
      </div>
    </div>
    <% end %>

app/views/users/settings.html.slim
- title t('.account_settings')
.container
  == render 'shared/flash_messages'
  .page-header
    h1= yield :title
  p.lead= t('.user_profile_details')
  = bootstrap_form_for @user, validate: true, html: { class: 'form-horizontal' } do |f|
    = f.error_messages
    legend= t('.application_settings')
    fieldset
      .form-group= f.select :locale, options_for_select(I18n.available_locales.map{ |locale| [ t('lang_native_name', locale: locale), locale] }, @user.locale), {} , disabled: (I18n.available_locales.one?)
      .form-group= f.time_zone_select :time_zone, nil, {}, html: { class: 'form-control' }
      .form-group
        .col-sm-10.col-sm-offset-2
          = label_tag :notification_group, t('.send_email'), class: 'control-label'
          .controls
            = f.check_box :send_email_messages
            = f.check_box :send_email_references
            p.help-block
              = t('.send_email_at_address', email: content_tag(:b,current_user.email)).html_safe
      .form-group= f.button type: 'submit', class: 'btn btn-primary', data: { disable_with: t('helpers.disable_with') }

app/views/users/show.html.slim
- title @user
.container
  .row
    .col-sm-3.text-center-sm
      = user_profile_picture @user, size: nil, type: :large, style: 'img-responsive heading-margins'
    .col-sm-9
      h1.no-margin-bottom= @user
      p.text-muted
        small= t('.member_since', date: l(@user.created_at.to_date, format: :month_year))
      - if @user.bio?
        blockquote.user-blockquote
          p= @user.bio
      blockquote.facebook-verified-blockquote
        - if @user.facebook?
          span.facebook-verified
            span.fa.fa-check<>
            = User.human_attribute_name(:facebook_verified)
          br
          span.text-muted= t('.facebook_verified')
        - else
          span.facebook-verified
            span.fa.fa-check<>
            = 'Verified through email'
          br
          span.text-muted= 'Your registered email id has been verified'
      .tag-list
        .tag.tag-icare= Reference.model_name.human(count: :lot)
        = reference_tags @user
        = link_to t('.see_all'), user_references_path(@user), class: 'tag'
        .tag.tag-facebook= t('.basic_info')
        .tag= t('.age', count: @user.age)
        .tag= @user.gender
        = language_tags @user
        = mutual_friends @user, current_user
        = work_and_education_tags @user, :education
        = work_and_education_tags @user, :work
        = favorite_tags @user, @user.facebook_favorites