config/routes.rb
Rails.application.routes.draw do

  get 'ports/suggest'

  get 'ports/route'

  get 'testing/new'

  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    # delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  root to: 'pages#home'

  resources :conversations, only: [:show, :new, :create, :update, :index] do
    get :unread, on: :collection
    resources :messages, only: [:create]
  end

  resources :feedbacks, only: [:show, :new, :create, :edit, :update, :destroy, :index]

  resources :itineraries, only: [:show, :new, :create, :edit, :update, :destroy, :index, :search] do
    post :search, on: :collection
    resources :build
  end

  resources :notifications, only: :index

  resources :users, constraints: { id: /[A-Za-z0-9\.]+/ }, only: [:create ,:show, :update, :destroy] do
    get :itineraries, on: :member
    resources :references, only: [:show, :new, :create, :update, :index]
  end

  # Admin Area
  namespace :admin do
    resources :users, only: [:index] do
      get :login_as, on: :member
      post :ban, :unban, on: :member
    end
  end

  mount Resque::Server, at: '/resque' if defined?(Resque::Server)

  # Root route aliases
  get :dashboard, to: 'users#dashboard'
  get :settings, to: 'users#settings'
  get :banned, to: 'users#banned'

  get :about, to: 'pages#about'
  get :how_it_works, to: 'pages#how_it_works'
  get :policy, to: 'pages#policy'
  get :terms, to: 'pages#terms'
  get :demo_terms, to: 'pages#demo_terms'
  get :fbjssdk_channel, to: 'pages#fbjssdk_channel'
  post :report_uri, to: 'pages#report_uri'

  post :search_itineraries_new, to: 'itineraries#new_search'

end

app/models/feedback.rb
class Feedback
  include Mongoid::Document
  include Mongoid::Timestamps

  TYPE = %w(bug idea location)
  STATUS = ['open', 'fixed', 'in progress', 'not applicable']

  belongs_to :user
  delegate :name, to: :user, prefix: true, allow_nil: true

  field :type, type: String, default: 'bug'
  field :message, type: String
  field :url, type: String
  field :status, type: String, default: 'open'

  validates :type, inclusion: TYPE, presence: true
  validates :status, inclusion: STATUS, presence: true
  validates :message, presence: true

  def fixed?
    status == 'fixed'
  end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController

  before_action :set_feedback, only: [:show, :edit, :update, :destroy]
  before_action :check_owner_or_admin, only: [:edit, :update, :destroy]

  def index
    @feedbacks = Feedback.includes(:user).all.desc(:updated_at).page params[:page]
    @feedbacks = @feedbacks.where(:status.ne => 'fixed') if params[:hide_fixed]
    @url = request.env['HTTP_REFERER']
  end

  def new
    @feedback = Feedback.new(url: params[:url])
  end

  def create
    @feedback = current_user.feedbacks.build(permitted_params.feedback)
    if @feedback.save
      redirect_to feedbacks_path, flash: { success: t('flash.feedbacks.success.create') }
    else
      render :new
    end
  end

  def update
    if @feedback.update_attributes(permitted_params.feedback)
      redirect_to feedbacks_path, flash: { success: t('flash.feedbacks.success.update') }
    else
      render :edit
    end
  end

  def destroy
    @feedback.destroy
    redirect_to feedbacks_path, flash: { success: t('flash.feedbacks.success.destroy') }
  end

  private
  def set_feedback
    @feedback = Feedback.find(params[:id])
  end

  def check_owner_or_admin
    redirect_to :dashboard, flash: { error: t('flash.errors.not_allowed') } unless current_user.admin? || current_user == @feedback.user
  end
end

app/views/feedbacks/_form.html.slim
= bootstrap_form_for @feedback, validate: true do |f|
  = f.error_messages
  = f.select :type, Feedback::TYPE
  - if permitted_params.feedback_attributes.include? :status
    = f.select :status, Feedback::STATUS
  = f.text_area :message, rows: 8
  = f.text_field :url
  = f.submit class: 'btn btn-primary', data: { disable_with: t('helpers.disable_with') }

app/views/feedbacks/edit.html.slim
- title t 'helpers.titles.edit', model: Feedback.model_name.human
.container
  .page-header
    h1= yield :title
  == render 'form'

app/views/feedbacks/index.html.slim
- title Feedback.model_name.human(count: :lot)
.container
  == render 'shared/flash_messages'
  .page-header
    h1= yield :title
    .btn-toolbar
      = link_to t('helpers.links.new'), new_feedback_path, class: 'btn btn-primary'
      - if params[:hide_fixed]
        = link_to t('.show_fixed'), feedbacks_path, class: 'btn btn-default'
      - else
        = link_to t('.hide_fixed'), feedbacks_path(hide_fixed: true), class: 'btn btn-default'
  .table-responsive
    table.table
      thead
        tr
          th= Feedback.human_attribute_name(:type)
          th= Feedback.human_attribute_name(:status)
          th= User.model_name.human
          th= Feedback.human_attribute_name(:message)
          th= Feedback.human_attribute_name(:updated_at)
          th=t '.actions', default: t('helpers.actions')
      tbody
        - for feedback in @feedbacks
          tr.vertical-align-middle class=('success' if feedback.fixed?)
            td= feedback.type
            td= feedback.status.upcase
            td
              - if feedback.user?
                = link_to feedback.user_name, user_path(feedback.user)
              - else
                span.text-muted= t('former_user')
            td= link_to feedback.message.truncate(100), feedback_path(feedback)
            td= l feedback.updated_at, format: :long
            td
              .btn-toolbar
                - if current_user == feedback.user || current_user.admin?
                  = link_to edit_feedback_path(feedback), class: 'btn btn-xs btn-default' do
                    span.fa.fa-pencil<>
                    = t('helpers.links.edit')
                  = link_to feedback_path(feedback), method: :delete, data: { confirm: t('helpers.links.confirm') }, class: 'btn btn-xs btn-danger' do
                    span.fa.fa-times<>
                    = t('helpers.links.destroy')
  == paginate @feedbacks

app/views/feedbacks/new.html.slim
- model_class = @feedback.class
.container
  .page-header
    h1=t '.title', default: t('helpers.titles.new', model: model_class.model_name.human, default: "New # model_class.model_name.human ")
  == render 'form'

app/views/feedbacks/show.html.slim
- title Feedback.model_name.human
.container
  .page-header
    h1= yield :title

  p
    strong= User.model_name.human
    br
    - if @feedback.user?
      = link_to @feedback.user_name, user_path(@feedback.user)
    - else
      span.text-muted= t('former_user')
  p
    strong= Feedback.human_attribute_name(:type)
    br
    = @feedback.type
  p.pre-line
    strong= Feedback.human_attribute_name(:message)
    br
    = @feedback.message.strip.gsub(/\r/, '')
  p
    strong= Feedback.human_attribute_name(:url)
    br
    = link_to @feedback.url, @feedback.url
  .btn-toolbar
    = link_to t('.back', default: t('helpers.links.back')), feedbacks_path, class: 'btn btn-default'
    = link_to t('.edit', default: t('helpers.links.edit')), edit_feedback_path(@feedback), class: 'btn btn-default'